# Generated by Django 3.0.3 on 2020-09-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200905_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='invoice_number',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='api.FileInfo'),
        ),
    ]
