# Generated by Django 3.0.3 on 2020-09-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vendor_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice_number',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='api.FileInfo'),
        ),
    ]
